apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 403963833479.dkr.ecr.ap-southeast-1.amazonaws.com/simplebank:90371e0893c25cfbc126f0b7ab66c6224463b56c
          ports:
            - containerPort: 8080